### ISSUE TITLE
HTTPS connection issue

### ISSUE THREAD

**Issue by jonathanweinberg** [hassio-addons/addon-ide#6]
# Problem/Motivation

Upon setting `ssl": true`, install with Hass.io Plugin DuckDNS Version `1.1` (w/ working LetsEncrypt via that same plugin), the connection to the URL for the IDE is refused.
 
## Expected behavior

> The IDE to show up and work via HTTPS.

#### Existing open tab will not reconnect.

Cloud 9 IDE / Plugin Log Error ~ Existing Tab:
```
2018/02/27 12:05:27 [info] 666#666: *122 client closed connection while waiting for request, client: LOCALSUBNETIP, server: 0.0.0.0:8321
```

#### New browser tabs provoke the error below.

Cloud 9 IDE / Plugin Log Error ~ New Tab:
```
2018/02/27 12:06:27 [warn] 666#666: no resolver defined to resolve ocsp.int-x3.letsencrypt.org while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org, certificate: "/ssl/fullchain.pem"
```

## Steps to reproduce

Here is some background / environmental information below...

No other Nginx plugin or running.

#### Environmental Info
* Cloud 9 IDE Version `0.1.0`
* HA Version `64.0`
* Hass.io Version `1.21`
* Supervisor Version `0.95`
* Raspberry Pi 3
* Ethernet connection, router DHCP reserved "static" IP.
* Configuration.yaml setting:
```
http:
  api_password: !secret http_password
  ssl_certificate: !secret http_ssl_certificate
  ssl_key: !secret http_ssl_key
  base_url: sitename.duckdns.org
```
* Secrets.yaml
```
http_password: 1234567890ABC
http_ssl_certificate: '/ssl/fullchain.pem'
http_ssl_key: '/ssl/privkey.pem'
```
